name: Daily LinkedIn Job Tracker

on:
  schedule:
    # Runs every day at 9:00 AM UTC (adjust timezone as needed)
    # For IST (India): 9 AM UTC = 2:30 PM IST
    # For PST: 9 AM UTC = 1 AM PST
    # For EST: 9 AM UTC = 4 AM EST
    - cron: '0 9 * * *'
  
  # Also allows manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  track-jobs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create credentials.json from secret
      run: |
        echo '${{ secrets.GOOGLE_CREDENTIALS }}' > credentials.json
    
    - name: Run job tracker
      run: |
        python linkedin_job_tracker.py
    
    - name: Commit and push if JSON changed (backup)
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add linkedin_pm_jobs.json || true
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update job listings - $(date)" && git push)
